### ISSUE TITLE
Corrigir o erro de tipagem do `express` ao injetar a propriedade `user` ao `request`

### ISSUE THREAD

**Issue by kaique-soares** [filipegramlich/nodets1#1]
## Contexto

Quando um usuário vai atualizar seus dados ele precisa estar logado, com isso, para garantir a autenticação o @filipegramlich criou o middleware `ensureAuthenticated`:

https://github.com/filipegramlich/nodets1/blob/d75fbf1e0a70496ffc18b2a4061a115e859681bd/src/routes/users.routes.ts#L11

E após a autenticidade do usuário ser comprovada, é injetado na `request` do `express` o objeto `user`:

https://github.com/filipegramlich/nodets1/blob/d75fbf1e0a70496ffc18b2a4061a115e859681bd/src/middleware/ensureAuthenticated.ts#L21-L23

No entanto, está dando erro de tipagem mesmo depois do @filipegramlich criar o arquivo de definição de tipos do `express`:

https://github.com/filipegramlich/nodets1/blob/d75fbf1e0a70496ffc18b2a4061a115e859681bd/src/express.d.ts#L1-L13

## Execução

- [x] Entender o porquê do erro de tipagem
- [x] Corrigir o erro de tipagem

**Comment by kaique-soares** [comment]
@filipegramlich vou baixar o projeto e investigar o que pode estar causando o erro :+1: :handshake: 

Vou notificando o progresso das coisas por aqui :+1:

**Comment by kaique-soares** [comment]
@filipegramlich problema resolvido :tada: :tada: :tada:

Na seção de **execução** desta issue eu adicionei 2 itens para separar o problema: `Entender o porquê do erro de tipagem` e `Corrigir o erro de tipagem`:

![image](https://user-images.githubusercontent.com/57193392/229307763-430c41bb-d742-479e-bcee-872a84ea9631.png)

No entanto, você já resolveu o item `Corrigir o erro de tipagem` quando adicionou o arquivo `express.d.ts`, olha só:

- Sem as definições de tipos acusa o erro de **type checking**, corretamente:

![image](https://user-images.githubusercontent.com/57193392/229307989-8e7c1550-acfe-46fb-86d1-46721d990e90.png)

- Com as definições de tipos não acusa o erro, como esperado:

![image](https://user-images.githubusercontent.com/57193392/229308145-d1aa2ef3-6287-4ffe-8265-254aa09d9dba.png)

Então, o item `Corrigir o erro de tipagem` já está feito :tada::

![image](https://user-images.githubusercontent.com/57193392/229308294-62cd591b-a2e3-466e-9be6-13fbf0d21a36.png)

Mas pensar nele foi o que me levou a entender o porquê do erro de tipagem ao rodar o servidor com o comando `npm run dev`:

![image](https://user-images.githubusercontent.com/57193392/229308408-0bc33e43-497c-47e6-91d7-4699146076d0.png)

Repare que o log mostrado no terminal aponta o `ts-node` como vetor do erro e que o erro é de **type checking**, mas o erro de **type checking você já resolveu**, então, podemos dizer para o **`ts-node` não checar os tipos** mas **apenas transpilar** o código TypeScript.

E seguindo a [documentação do ts-node](https://typestrong.org/ts-node/docs/options), temos a opção `transpileOnly` que serve exatamente para o que precisamos:

![image](https://user-images.githubusercontent.com/57193392/229308729-e3d427f3-d7e3-4d7a-98af-d6ec0d39676c.png)

Com isso, basta habilitar ela dentro do `tsconfig.json`:

![image](https://user-images.githubusercontent.com/57193392/229308843-f6fed965-2563-46d8-aed7-f03eedc11378.png)

E rodando o servidor com o comando `npm run dev`, sucesso :tada:

![image](https://user-images.githubusercontent.com/57193392/229308896-f9e5a3a8-ed67-42aa-8cca-025d95b36321.png)

Então o item `Entender o porquê do erro de tipagem` acaba de ser concluído :handshake: 

![image](https://user-images.githubusercontent.com/57193392/229308993-f6bac164-571f-47c6-a336-b1ae13e7bf61.png)

---

@filipegramlich fez sentido?

**Comment by filipegramlich** [comment]
Opa , @kaique-soares! 😁 Muito obrigado pela ajuda cara e, fez sentido sim, mas ainda estou com uma dúvida: 

### Fatos 🧐

1. Existiam dois problemas : 

   - Type checking
   - Transpilação do código pelo TS-Node 
   
2. O primeiro problema, type checking, foi resolvido primeiro e em seguida resolvemos o segundo apenas dizendo para o ts-node não checar os tipos mas sim, só transpilar.

E é aqui que minha dúvida surge. Pois, se o type-checking teria sido resolvido, logo não temos mais erro de tipo, correto ? Então porque o ts-node ao conferir os tipos estava acusando erro ? 🤔

Posso assumir que é um erro interno do ts-node mesmo ou tem um passo lógico que está falhando ?

@kaique-soares , deu para entender a duvida ?

**Comment by kaique-soares** [comment]
> @kaique-soares , deu para entender a duvida ?
Sim, deu para entender e inclusive foram ótimas @filipegramlich :+1: 

> E é aqui que minha dúvida surge. Pois, se o type-checking teria sido resolvido, logo não temos mais erro de tipo, correto ?

Sim, correto. Você resolveu ele quando adiciou o `express.d.ts`

> Então porque o ts-node ao conferir os tipos estava acusando erro ?

O `ts-node` (e até mesmo o `typescript`) por padrão olha para os tipos que estão dentro da pasta `node_modules/@types/`

![image](https://user-images.githubusercontent.com/57193392/229313875-af18f8f8-8992-4563-a88c-6fa7021cb1e0.png)

Quando você criou o arquivo `express.d.ts` você avisou o `typescript` que era para ele considerar esse arquivo também mas o `ts-node` não, porque ele continua olhando apenas para a pasta `node_modules/@types/express`.

> Posso assumir que é um erro interno do ts-node mesmo ou tem um passo lógico que está falhando ?

Não diria que é um erro interno do `ts-node` porque ele olha de fato para os tipos que estão definidos dentro da `node_modules/@types/`, então, eu diria que é mais uma limitação dele mesmo. No sentido de não conseguir considerar os arquivos de definição de tipos customizados, como o `express.d.ts`, por exemplo.

Observação: Eu não cheguei a olhar se o `ts-node` tem alguma configuração em relação à habilitar que ele olhe para arquivos `.d.ts` adicionais :+1: :handshake: 

---

Respondidas as dúvidas? Caso tenha ficado (ou gerado) mais alguma dúvida, fique à vontade para perguntar :handshake:

**Comment by filipegramlich** [comment]
Aaaagora sim tudo se encaixou @kaique-soares 👌.  O erro + as soluções fazem sentido. 

Só fico encucado mesmo por que em outros projetos, como os seus próprios esse erro não ocorreu mas sim nesse em especifico, sabe ? E também se eu poderia ter feito/posso fazer algo para evitar que se repita. 

Alguma sugestão, @kaique-soares ? 🤔

**Comment by kaique-soares** [comment]
Massa @filipegramlich :star_struck: :star_struck: :star_struck: 

> Só fico encucado mesmo por que em outros projetos, como os seus próprios esse erro não ocorreu mas sim nesse em especifico, sabe? 

Não havia parado para pensar nisso, ótimo ponto :+1: Muito curioso mesmo :thinking: e sinceramente não faço ideia :smile:

> E também se eu poderia ter feito/posso fazer algo para evitar que se repita.
> Alguma sugestão, @kaique-soares ?

Em trocaria o `ts-node` (ou `ts-node-dev`) pelo [`tsx`](https://www.npmjs.com/package/tsx), se uma tecnologia não me atende e a substituição dela não vai impactar o projeto, eu troco sem remorsos :smile:

**Comment by filipegramlich** [comment]
Kkkk beleza, vou testar essa substituição para ver o resultado mesmo.

Novamente, muuuito obrigado, @kaique-soares ! Tamo junto manin 😄🤝

**Comment by kaique-soares** [comment]
> Kkkk beleza, vou testar essa substituição para ver o resultado mesmo.

Utilizando o `tsx` tu já elimina a necessidade do `nodemon` e do `ts-node` :+1:
